export const USER_DATA = "USER_DATA";

export const ARTICLE_DATA = "ARTICLE_DATA";
export const ARTICLE_LIST = "ARTICLE_LIST";

export const CHALLENGE_DATA = "CHALLENGE_DATA";
export const CHALLENGE_DAILY_DATA = "CHALLENGE_DAILY_DATA";
export const CHALLENGE_WEEKLY_DATA = "CHALLENGE_WEEKLY_DATA";
export const CHALLENGE_ENDED_DATA = "CHALLENGE_ENDED_DATA";

export const CHALLENGE_CATEGORY_DATA = "CHALLENGE_CATEGORY_DATA";
export const CHALLENGE_ARTICLE_LIST = "CHALLENGE_ARTICLE_LIST";

export const CHALLENGE_SUGGESTION_LIST = "CHALLENGE_SUGGESTION_LIST";
