export const USER_DATA = "USER_DATA";

export const ARTICLE_DATA = "ARTICLE_DATA";
export const ARTICLE_LIST = "ARTICLE_LIST";

export const CHALLENGE_DATA = "CHALLENGE_DATA";
export const CHALLENGE_CATEGORY_DATA = "CHALLENGE_CATEGORY_DATA";
export const CHALLENGE_ARTICLE_LIST = "CHALLENGE_ARTICLE_LIST";
